modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/RaphyTwin/SnapLook/issues"
license = "LGPL-3.0"

[[mods]]
modId = "snaplook"
version = "${version}"
displayName = "SnapLook"
authors = "RaphyTwin"
description = '''
A simple SnapLook mod like in Lunar Client
'''

[[dependencies.snaplook]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snaplook]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snaplook]]
modId = "architectury"
type = "required"
versionRange = "[16.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "snaplook.mixins.json"
